apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cloud-build-nginx
  labels:
    app: demo-cloud-build-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-cloud-build-nginx
  template:
    metadata:
      labels:
        app: demo-cloud-build-nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/lil-onboard-gcp/onboard:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-cloud-build-nginx
spec:
  selector:
    app: demo-cloud-build-nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer